image:
  repository: ghcr.io/krishnakumar-sudala/users-service
  tag: "1769808246"

service:
  port: 3000

env:
  NODE_ENV: "development"
  POSTGRES_HOST: "postgres-dev"
  POSTGRES_DB: "usersdb"
  POSTGRES_USER: "usersadmin"

secretEnv:
  POSTGRES_PASSWORD: "dev-password"
  JWT_SECRET: "dev-jwt"
  JWT_REFRESH_SECRET: "dev-refresh"

