image:
  repository: ghcr.io/krishnakumar-sudala/users-service
  tag: "dev-latest"   # Your CI pipeline will overwrite this with the real tag

service:
  port: 3000

env:
  NODE_ENV: "production"
  POSTGRES_HOST: "postgres-prod"
  POSTGRES_DB: "usersdb"
  POSTGRES_USER: "usersadmin"

secretEnv:
  POSTGRES_PASSWORD: "prod-password"
  JWT_SECRET: "prod-jwt"
  JWT_REFRESH_SECRET: "prod-refresh"
