image:
  repository: ghcr.io/krishnakumar-sudala/users-service
  tag: "dev-latest"   # Your CI pipeline will overwrite this with the real tag

service:
  port: 3000

env:
  NODE_ENV: "staging"
  POSTGRES_HOST: "postgres-staging"
  POSTGRES_DB: "usersdb"
  POSTGRES_USER: "usersadmin"

secretEnv:
  POSTGRES_PASSWORD: "staging-password"
  JWT_SECRET: "staging-jwt"
  JWT_REFRESH_SECRET: "staging-refresh"
