image:
  repository: ghcr.io/krishnakumar-sudala/users-service
  tag: "1771261973"

route:
  host: users-service-dev.apps-crc.testing

service:
  port: 3000

env:
  NODE_ENV: "development"
  POSTGRES_HOST: "postgresql.shared-services.svc.cluster.local"
  POSTGRES_DB: "platform"
  POSTGRES_USER: "postgres"
  PGSCHEMA: "users_service"
  
secretEnv:
  POSTGRES_PASSWORD: "postgres"
  JWT_SECRET: "dev-jwt"
  JWT_REFRESH_SECRET: "dev-refresh"

